name: publish-to-github-packages
run-name: Publish to Github Packages
on:
  push:
    branches:
      - main
    tags:
      - v0.*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
  publish-to-github-packages:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: npm install
      - run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - run: npm version ${{ env.version }} --allow-same-version
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
